services:
  db:
    image: postgres:16.8
    container_name: postgres
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - "5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  backend:
    build:
      context: ./backend
    container_name: backend
    restart: unless-stopped
    env_file: ./backend/.env
    ports:
      - "8000:8000"
    depends_on:
      - db
    command: sh -c "npx prisma migrate deploy && node dist/main"

  frontend:
    build:
      context: ./frontend
      args:
        VITE_API_URL: /api
    container_name: frontend
    restart: unless-stopped
    ports:
      - "80:80"
    depends_on:
      - backend

volumes:
  pgdata:
