version: '3.8'

services:
  db:
    image: postgres:16.8
    container_name: postgres
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  backend:
    build:
      context: ./backend
    container_name: backend
    restart: unless-stopped
    env_file: ./backend/.env
    ports:
      - "5000:3000"
    depends_on:
      - db

  frontend:
    build:
      context: ./frontend
    container_name: frontend
    restart: unless-stopped
    ports:
      - "80:80"
    depends_on:
      - backend

volumes:
  pgdata:
