services:
  db:
    image: postgres:16.8
    container_name: postgres
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - "5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  backend:
    build:
      context: ./backend
      args:
        BUILD_DATE: ${BUILD_DATE:-dev}
    container_name: backend
    restart: unless-stopped
    env_file: ./backend/.env
    ports:
      - "8000:8000"
    depends_on:
      - db
    command: sh -c "npx prisma migrate deploy && node dist/main"
    volumes:
      - ./backend/public:/app/public

  frontend:
    build:
      context: ./frontend
      args:
        VITE_API_URL: /api
        BUILD_DATE: ${BUILD_DATE:-dev}
    container_name: frontend
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - backend
    volumes:
      - /etc/letsencrypt:/etc/letsencrypt:ro

volumes:
  pgdata:
