import type { Metadata } from "next";
import MainToolbar from "@/components/MainToolBar/MainToolbar";
import QueryProvider from "@/components/QueryProvider/QueryProvider";
import './globals.css';
import 'bootstrap/dist/css/bootstrap.min.css';
import {ToastContainer} from "react-toastify";

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
                                       children,
                                   }: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
        <body>
        <QueryProvider>
            <ToastContainer/>
            <header>
                <MainToolbar/>
            </header>
            {children}
        </QueryProvider>
        </body>
        </html>
    );
}
